# Generated by Django 4.1.6 on 2023-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlist_id_alter_auctionlist_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('currentclub', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=20)),
                ('image_url', models.ImageField(blank=True, default=None, max_length=228, null=True, upload_to='')),
            ],
        ),
    ]
