# Generated by Django 4.1.6 on 2023-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Age',
            field=models.IntegerField(default=1),
        ),
    ]
