# Generated by Django 4.1.6 on 2023-05-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Position',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
