# Generated by Django 4.1.6 on 2023-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mobilenumber',
            field=models.IntegerField(default=1),
        ),
    ]
