# Generated by Django 4.1.6 on 2023-05-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_player_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Position',
            new_name='position',
        ),
    ]
