# Generated by Django 4.1.6 on 2023-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_position_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contactNo',
            field=models.IntegerField(default=1),
        ),
    ]
