# Generated by Django 4.1.6 on 2023-05-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Password',
            new_name='password',
        ),
    ]
