# Generated by Django 2.2.7 on 2023-05-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_password_player_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image_url', models.ImageField(blank=True, default=None, max_length=228, null=True, upload_to='')),
                ('status', models.CharField(default='No', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='auctionreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='No', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_list',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='bid_win_list',
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='auctionlist',
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='winner',
        ),
        migrations.AddField(
            model_name='auctionreg',
            name='clubname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Club'),
        ),
        migrations.AddField(
            model_name='auctionreg',
            name='playername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Player'),
        ),
    ]
