# Generated by Django 2.2.7 on 2023-05-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20230524_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionreg',
            name='clubname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Club'),
        ),
        migrations.AlterField(
            model_name='auctionreg',
            name='playername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Player'),
        ),
    ]
