# Generated by Django 2.2.7 on 2023-05-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20230524_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionreg',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
    ]
