# Generated by Django 2.2.7 on 2023-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auction_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start',
        ),
        migrations.AddField(
            model_name='auction',
            name='end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
